driver:
  name: vagrant
  boot_timeout: 1200
  gui: false

provisioner:
  name: chef_zero
  client_rb:
    environment: test-env

verifier:
  name: inspec

transport:
  name: winrm
  elevated: true
  username: Administrator
  password: Pass@word1

platforms:
  - name: windows-2012R2

suites:
  - name: default
    data_bags_path: test/integration/default/data_bags
    run_list:
      - recipe[apache_tomcat_windows::default]
    verifier:
      inspec_tests:
        - test/recipes/install.rb
        - test/recipes/solr.rb
