driver:
  name: vagrant
  boot_timeout: 1200
  gui: false

provisioner:
  name: chef_zero
  environments_path: ..\..\environments
  roles_path: ..\..\roles
  client_rb:
    environment: emg-stage

verifier:
  name: inspec

transport:
  name: winrm
  elevated: true
  username: Administrator
  password: Pass@word1

platforms:
  - name: windows-2012R2

suites:
  - name: default
    run_list:
      - recipe[apache_tomcat_windows::install]
    verifier:
      inspec_tests:
        - test/recipes/install.rb
        - test/recipes/solr.rb
    attributes:
      ftp_active_mode: false
